### ISSUE TITLE
如何修改主题颜色。

### ISSUE THREAD

**Issue by zhujinhu21** [mvpleung/vue-flipclock#10]
和官网上点主题颜色不一样，我想自己修改主题，修改哪个地方的值

**Comment by mvpleung** [comment]
Vue组件没有添加 Scoped，也就意味着你可以通过覆盖 CSS class 的形式来修改，具体的样式表名称请参考 src/flipclock.css

**Comment by zhujinhu21** [comment]
我在head中覆盖了class css样式，写在head中，但是生成的页面flipclock的样式会插入到我写的style样式的后面，覆盖了我写的class

**Comment by mvpleung** [comment]
不要写在Head中，你在什么地方使用的就写在什么地方，或者给组件添加父级样式用来约束

**Comment by zhujinhu21** [comment]
好的，我options中设置了autoStart:false, 在方法中调用this.$refs.flipclcok.start(); 不会开始计时，使用this.options.autoStart=true 会开始计时

**Comment by mvpleung** [comment]
我这边测试没问题，给个Demo吧

**Comment by zhujinhu21** [comment]
不好意思，我检查了下，this.$refs.flipclcok.start(); 我改成self.$refs.flipclcok.start(); 我是写在方法回调中的，谢谢
