### ISSUE TITLE
Is there any way I can add a callback to clock?

### ISSUE THREAD

**Issue by imkimchi** [mvpleung/vue-flipclock#3]
I want to add a callback function on stop, but seems like there's no documentation about callback feature. It would be really helpful if I could use callback feature, appreciate for making this awesome project :)

**Comment by mvpleung** [comment]
here [http://flipclockjs.com/#callbacks](http://flipclockjs.com/#callbacks)

**Comment by WSmonkey** [comment]
How to implement `callbacks` with your lib in Vue? The example you showed us is how the original library does. Thanks!

**Comment by mvpleung** [comment]
Document updated.
e.g.:
```
stop() {
  this.$refs.flipclock.stop(() => {
	alert('Stop !');
  })
}
```
