### ISSUE TITLE
怎么监听stop，然后重新启动？

### ISSUE THREAD

**Issue by WSmonkey** [mvpleung/vue-flipclock#6]
你好，我发现callbacks不work，所以想请问如何在Vue里面监听到stop 然后执行reset？

**Comment by mvpleung** [comment]
```
stop() {
  this.$refs.flipclock.stop(() => {
	alert('Stop !');
	this.reset();
  })
}
```

**Comment by WSmonkey** [comment]
谢谢。

我当时的做法是把stop 放到callbacks里，等监听到stop之后，自动执行callback，比如输出hello world。 但是发现hello world一直疯狂输出，然后就死了。。。

**Comment by WSmonkey** [comment]
Uncaught RangeError: Maximum call stack size exceeded

**Comment by mvpleung** [comment]
这里是Demo [https://github.com/mvpleung/vue-flipclock/blob/master/examples/base-vue.html](https://github.com/mvpleung/vue-flipclock/blob/master/examples/base-vue.html)

或者贴上你的示例代码看看

**Comment by mvpleung** [comment]
> 谢谢。
> 
> 我当时的做法是把stop 放到callbacks里，等监听到stop之后，自动执行callback，比如输出hello world。 但是发现hello world一直疯狂输出，然后就死了。。。

你这里说的把 stop 放到 callbacks 里，是那个 method 的 callback ？ 能否贴上示例代码

**Comment by web-wei** [comment]
怎么监听倒计时自己的事件，比如倒计时完了以后，不是主动触发

**Comment by mvpleung** [comment]
> 怎么监听倒计时自己的事件，比如倒计时完了以后，不是主动触发

文档已更新
```
options: {
	digit: 15,
	countdown: true,
	clockFace: 'DailyCounter',
	...
	callbacks: {
		stop: function () {
			alert('The clock has stopped!')
		}
	}
  }
```
